### ISSUE TITLE
awx services failed to start

### ISSUE THREAD

**Issue by arreyashu** [MrMEEE/awx-build#123]
After following installation procedure, the awx services do not start.  Some will start, then return to activating and then failed.  What is happening? 

activating
failed
failed
failed
activating
failed

**Comment by MrMEEE** [comment]
What does a:
```
systemctl status awx-cbreceiver.service awx-channels-worker.service awx-daphne.service awx-dispatcher.service awx-web.service
```
show you???

**Comment by arreyashu** [comment]
Thank you for the reply sir. Please see below for each service:

systemctl status -l awx-cbreceiver.service
● awx-cbreceiver.service - AWX cbreceiver service
   Loaded: loaded (/usr/lib/systemd/system/awx-cbreceiver.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Mon 2019-07-01 14:47:49 EDT; 1h 41min ago
  Process: 19922 ExecStart=/usr/bin/scl enable rh-python36 rh-postgresql10 awx-manage run_callback_receiver (code=killed, signal=TERM)
 Main PID: 19922 (code=killed, signal=TERM)

Jul 01 14:47:48 tsl-lab-awx-u001 systemd[1]: Started AWX cbreceiver service.
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: Stopping AWX cbreceiver service...
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: Stopped AWX cbreceiver service.
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: start request repeated too quickly for awx-cbreceiver.service
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: Failed to start AWX cbreceiver service.
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: Unit awx-cbreceiver.service entered failed state.
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: awx-cbreceiver.service failed.

systemctl status -l awx-daphne.service
● awx-daphne.service - AWX daphne service
   Loaded: loaded (/usr/lib/systemd/system/awx-daphne.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2019-07-01 16:30:10 EDT; 882ms ago
  Process: 22387 ExecStart=/usr/bin/scl enable rh-python36 rh-postgresql10 daphne -b 127.0.0.1 -p 8051 awx.asgi:channel_layer (code=exited, status=1/FAILURE)
 Main PID: 22387 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/awx-daphne.service

Jul 01 16:30:10 tsl-lab-awx-u001 systemd[1]: Unit awx-daphne.service entered failed state.
Jul 01 16:30:10 tsl-lab-awx-u001 systemd[1]: awx-daphne.service failed.

systemctl status -l awx-channels-worker.service awx-dispatcher.service
● awx-channels-worker.service - AWX channels worker service
   Loaded: loaded (/usr/lib/systemd/system/awx-channels-worker.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Mon 2019-07-01 14:47:49 EDT; 1h 43min ago
  Process: 19925 ExecStart=/usr/bin/scl enable rh-python36 rh-postgresql10 awx-manage runworker --only-channels 'websocket.*' (code=killed, signal=TERM)
 Main PID: 19925 (code=killed, signal=TERM)

Jul 01 14:47:48 tsl-lab-awx-u001 systemd[1]: Started AWX channels worker service.
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: Stopping AWX channels worker service...
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: Stopped AWX channels worker service.
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: start request repeated too quickly for awx-channels-worker.service
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: Failed to start AWX channels worker service.
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: Unit awx-channels-worker.service entered failed state.
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: awx-channels-worker.service failed.

● awx-dispatcher.service - AWX Dispatcher
   Loaded: loaded (/usr/lib/systemd/system/awx-dispatcher.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Mon 2019-07-01 14:47:49 EDT; 1h 43min ago
  Process: 19924 ExecStart=/usr/bin/scl enable rh-python36 rh-postgresql10 awx-manage run_dispatcher (code=killed, signal=TERM)
 Main PID: 19924 (code=killed, signal=TERM)

Jul 01 14:47:48 tsl-lab-awx-u001 systemd[1]: Started AWX Dispatcher.
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: Stopping AWX Dispatcher...
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: Stopped AWX Dispatcher.
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: start request repeated too quickly for awx-dispatcher.service
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: Failed to start AWX Dispatcher.
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: Unit awx-dispatcher.service entered failed state.
Jul 01 14:47:49 tsl-lab-awx-u001 systemd[1]: awx-dispatcher.service failed.
[root@tsl-lab-awx-u001 system]#

systemctl status -l awx-web.service
● awx-web.service - AWX web service
   Loaded: loaded (/usr/lib/systemd/system/awx-web.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2019-07-01 16:32:10 EDT; 865ms ago
  Process: 24015 ExecStart=/usr/bin/scl enable rh-python36 rh-postgresql10 uwsgi          --socket 127.0.0.1:8050          --module=awx.wsgi:application          --logto=/var/log/tower/web.log          --die-on-term          --vacuum          --uid awx          --gid awx          --processes=5          --harakiri=120          --no-orphans          --master          --max-requests=1000          --master-fifo=/var/lib/awx/awxfifo          --lazy-apps -b 32768 (code=exited, status=127)
 Main PID: 24015 (code=exited, status=127)

Jul 01 16:32:10 tsl-lab-awx-u001 systemd[1]: awx-web.service: main process exited, code=exited, status=127/n/a
Jul 01 16:32:10 tsl-lab-awx-u001 systemd[1]: Unit awx-web.service entered failed state.
Jul 01 16:32:10 tsl-lab-awx-u001 systemd[1]: awx-web.service failed.




________________________________

**Comment by MrMEEE** [comment]
Are you sure that all the dependencies are installed?

**Comment by arreyashu** [comment]
I am not sure. I followed the installation documentation and installed more dependencies along the way. Below are additional packages I installed before the following command could work:


sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage migrate"  ## This command will not complete without these packages

   19  20190628125136: yum install -y rh-python36-django-qsstats-magic.noarch
   22  20190628125203: yum install -y rh-python36-django-split-settings.noarch
   24  20190628125228: yum install rh-python36-ansiconv.noarch
   27  20190628125252: yum install rh-python36-python-memcached.noarch -y
   58  20190628125928: yum install rh-python36-prometheus_client.noarch -y
   63  20190628130220: yum install -y rh-python36-asn1crypto.noarch

I have done the installation like four times now on a fresh server every time.

Thanks for your help.

________________________________

**Comment by MrMEEE** [comment]
Seems like you forgot or had problems with installing the python-dependencies:

https://awx.wiki/multi-section-page/installation

What distro are you using?

**Comment by franzcisco** [comment]
Hi, I have the same issue.
Just upgraded to version 6.0.0 (in order to have systemd services) and then stopped/started AWX. All went fine.
Next I rebooted the VM, and now awx service keep looping "start>stopped" every few seconds.


here is the output from the same command you asked the previous user:


[devnet@VMW-DEVNET-AWX ~]$ systemctl status awx-cbreceiver.service awx-channels-worker.service awx-daphne.service awx-dispatcher.service awx-web.service
â— awx-cbreceiver.service - AWX cbreceiver service
   Loaded: loaded (/usr/lib/systemd/system/awx-cbreceiver.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-07-02 10:47:06 CEST; 2s ago
 Main PID: 21313 (scl)
   CGroup: /system.slice/awx-cbreceiver.service
           â”œâ”€21313 /usr/bin/scl enable rh-python36 rh-postgresql10 awx-manage run_callback_receiver
           â”œâ”€21320 /bin/bash /var/tmp/sclSu0Cye
           â””â”€21348 /opt/rh/rh-python36/root/usr/bin/python3 /opt/rh/rh-python36/root/usr/bin/awx-manage run_callback_receiver

Jul 02 10:47:06 VMW-DEVNET-AWX systemd[1]: Started AWX cbreceiver service.

â— awx-channels-worker.service - AWX channels worker service
   Loaded: loaded (/usr/lib/systemd/system/awx-channels-worker.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-07-02 10:47:06 CEST; 2s ago
 Main PID: 21312 (scl)
   CGroup: /system.slice/awx-channels-worker.service
           â”œâ”€21312 /usr/bin/scl enable rh-python36 rh-postgresql10 awx-manage runworker --only-channels 'websocket.*'
           â”œâ”€21315 /bin/bash /var/tmp/sclq9fkVd
           â””â”€21349 /opt/rh/rh-python36/root/usr/bin/python3 /opt/rh/rh-python36/root/usr/bin/awx-manage runworker --only-channels websocket.*

Jul 02 10:47:06 VMW-DEVNET-AWX systemd[1]: Started AWX channels worker service.

â— awx-daphne.service - AWX daphne service
   Loaded: loaded (/usr/lib/systemd/system/awx-daphne.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-07-02 10:47:06 CEST; 2s ago
 Main PID: 21316 (scl)
   CGroup: /system.slice/awx-daphne.service
           â”œâ”€21316 /usr/bin/scl enable rh-python36 rh-postgresql10 daphne -b 127.0.0.1 -p 8051 awx.asgi:channel_layer
           â”œâ”€21319 /bin/bash /var/tmp/scljRGsrd
           â””â”€21350 /opt/rh/rh-python36/root/usr/bin/python3 /opt/rh/rh-python36/root/usr/bin/daphne -b 127.0.0.1 -p 8051 awx.asgi:channel_layer

Jul 02 10:47:06 VMW-DEVNET-AWX systemd[1]: Started AWX daphne service.

â— awx-dispatcher.service - AWX Dispatcher
   Loaded: loaded (/usr/lib/systemd/system/awx-dispatcher.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-07-02 10:47:06 CEST; 2s ago
 Main PID: 21314 (scl)
   CGroup: /system.slice/awx-dispatcher.service
           â”œâ”€21314 /usr/bin/scl enable rh-python36 rh-postgresql10 awx-manage run_dispatcher
           â”œâ”€21317 /bin/bash /var/tmp/sclOKgsLd
           â””â”€21345 /opt/rh/rh-python36/root/usr/bin/python3 /opt/rh/rh-python36/root/usr/bin/awx-manage run_dispatcher

Jul 02 10:47:06 VMW-DEVNET-AWX systemd[1]: Started AWX Dispatcher.

â— awx-web.service - AWX web service
   Loaded: loaded (/usr/lib/systemd/system/awx-web.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-07-02 10:47:06 CEST; 2s ago
 Main PID: 21311 (scl)
   CGroup: /system.slice/awx-web.service
           â”œâ”€21311 /usr/bin/scl enable rh-python36 rh-postgresql10 uwsgi          --socket 127.0.0.1:8050          --module=awx.wsgi:application          --logto=/var/log/tower/web.lo...
           â”œâ”€21318 /bin/bash /var/tmp/sclS7HIHd
           â”œâ”€21343 uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/tower/web.log --die-on-term --vacuum --uid awx --gid awx --processes=5 --harakiri=120 -...
           â”œâ”€21351 uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/tower/web.log --die-on-term --vacuum --uid awx --gid awx --processes=5 --harakiri=120 -...
           â”œâ”€21352 uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/tower/web.log --die-on-term --vacuum --uid awx --gid awx --processes=5 --harakiri=120 -...
           â”œâ”€21353 uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/tower/web.log --die-on-term --vacuum --uid awx --gid awx --processes=5 --harakiri=120 -...
           â”œâ”€21354 uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/tower/web.log --die-on-term --vacuum --uid awx --gid awx --processes=5 --harakiri=120 -...
           â””â”€21355 uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/tower/web.log --die-on-term --vacuum --uid awx --gid awx --processes=5 --harakiri=120 -...

Jul 02 10:47:06 VMW-DEVNET-AWX systemd[1]: Started AWX web service.
[devnet@VMW-DEVNET-AWX ~]$

**Comment by franzcisco** [comment]
Update: although all the services seem to start OK, the actual aws service starts and stops immediately (and thus all the services re-enter the loop):

[devnet@VMW-DEVNET-AWX ~]$ systemctl status awx
â— awx.service - Application
   Loaded: loaded (/usr/lib/systemd/system/awx.service; enabled; vendor preset: disabled)
   Active: active (exited) since Tue 2019-07-02 10:55:37 CEST; 11s ago
  Process: 25702 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 25702 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/awx.service

Jul 02 10:55:37 VMW-DEVNET-AWX systemd[1]: Stopping Application...
Jul 02 10:55:37 VMW-DEVNET-AWX systemd[1]: Starting Application...
Jul 02 10:55:37 VMW-DEVNET-AWX systemd[1]: Started Application.
[devnet@VMW-DEVNET-AWX ~]$ 
[devnet@VMW-DEVNET-AWX ~]$ 

So probably there is some dependency broken. Is there a way to check which dependency is blocking awx?

**Comment by arreyashu** [comment]
I don’t think I missed any dependency.  Do you have a complete list of dependencies ? I am using centos 7.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MrMEEE** [comment]
What does:
```
yum -y install --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' -x *-debuginfo rh-python36*
```

give you of output??

**Comment by arreyashu** [comment]
I will do this and get back to you.

Thanks much

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by franzcisco** [comment]
Hi Martin,

 

thanks for all the answers (I do not know how you manage…).

I just did a new/fresh deploy and clered up through the instructions (only one drawback , see * below).

 

This time services wotk fine, or at leest awx starts and does not stop – it remains up.

I do have a new issue though: I cannot access the web interface ☹.

 

If I try to access my new VM with AWX I get a “connection refused”.

However, nginx is running, awx is running, everything seems to be running.

Firewalld is disabled so that’s not it.

 

I am running out of options but still I cannot access the GUI… 

I am thinking of opening a new thread for this, but maybe it is a “too simple issue”. Let me know (whenever you can, no worries).

 

THANKS A LOT,

 

Francisco

 

(*) I just got an error on the Configuration step with “scl enable rh-postgresql10 "su postgres -c \"createuser -S awx\""” – it gave me “cannot change to directoty usr/devnet” or something. Issuing it again however stated that there was “nothing to do – user already existed”.

**Comment by MrMEEE** [comment]
Hi

is port 8052 open?
output of:
```
ss -ntpa
```
You can ignore the error from the postgres command.. it's just that you try to access a folder from the postgres user, that it doesn't have access to.. but it still creates the user...

**Comment by franzcisco** [comment]
It seems to be, but it is not linked to any IP/interface:

 

[devnet@vmw-devnet-awx ~]$ ss -ntpa | grep LISTEN

LISTEN     0      128          *:25672                    *:*                  

LISTEN     0      128          *:11211                    *:*                  

LISTEN     0      128          *:4369                     *:*                  

LISTEN     0      100    127.0.0.1:8050                     *:*                  

LISTEN     0      50     127.0.0.1:8051                     *:*                  

LISTEN     0      128          *:8052                     *:*                  

LISTEN     0      128          *:22                       *:*                  

LISTEN     0      128    127.0.0.1:5432                     *:*                  

LISTEN     0      100    127.0.0.1:25                       *:*                  

LISTEN     0      128         :::5672                    :::*                  

LISTEN     0      128         :::11211                   :::*                  

LISTEN     0      128         :::4369                    :::*                  

LISTEN     0      128         :::22                      :::*                  

LISTEN     0      128        ::1:5432                    :::*                  

LISTEN     0      100        ::1:25                      :::*                  

[devnet@vmw-devnet-awx ~]$

 

 

Any clues?

 

/f

**Comment by MrMEEE** [comment]
The * means that it listens to all interfaces..

are you sure that you are not on a network that blocks port 8052?..

What if you do a:
```
curl http://localhost:8052
```
on the awx-rpm vm?

**Comment by franzcisco** [comment]
Curl works fine! 😊

You nailed it… I tried http://<my_ip>:8052 and actually it also works from the web browser, I just need to add the 8052 port.

I thought nginx would take care of this…

Maybe I have something wrong in my nginx config?

 

F.

**Comment by MrMEEE** [comment]
Nope.. by default it runs on 8052 (legacy reasons)... you can just change it if you want to.. just replace 8052 in your nginx.conf with 80..

**Comment by franzcisco** [comment]
Just a quick feedback: all OK in my deployment. Martin, you rock!
