### ISSUE TITLE
awx.service dependencies

### ISSUE THREAD

**Issue by MrMEEE** [MrMEEE/awx-build#133]
Got this from Ville Ojamo..

I am running on PGSQL11 installed from PGDG repository (no problems with this setup so far) and going with native python3 package would allow me to get rid of SCL. I am also using Apache instead of nginx.

The above two variations from the standard install causes the "awx.service" systemd unit to not be usable since it Requires nginx.service and rh-postgresql10-postgresql.service. This is just my opinion but are those requirements important?

It would make sense to me that the "awx.service" would only control the AWX-specific services. Then the standard unit file could be used for non-standard installations as well. I understand if you're hesitant to do that and I'm fine with keep modifying the file in my Ansible plays after install/upgrade - after all I made the decision to deviate from the standard install.

**Comment by eperegudov** [comment]
Hi!
Have same issue, there is one workaround. As follow from systemd unit's documentation: if you want to remove dependencies, you have to override the entire unit. Just copy original "awx.service" to /etc/systemd/system/awx.service and remove unwanted dependencies from that unit. Enjoy!

I guess, that may be more correct is to use Requisite or Wants directives instead of Requires.

**Comment by MrMEEE** [comment]
maybe I should do a awx-standalone and a awx-external target :)
