### ISSUE TITLE
AWX job not started

### ISSUE THREAD

**Issue by Ashjoker24** [MrMEEE/awx-build#148]
Hi MrMEEE I completely installed AWX-RPM and i sucecessfully logged in in that dashboard. When i try to run a job it is in pending state for more than hour and it not execute. I checked the log but all are clear.
![image](https://user-images.githubusercontent.com/43417210/64260117-ee59c900-cf47-11e9-811d-ae9fb510f424.png)

**Comment by ainaomotayo** [comment]
I'm facing the same thing. 
@Ashjoker24 did you manage to get it running?

**Comment by MrMEEE** [comment]
hmm.. can you try to do a "systemctl status awx-*"

Also, which logs have you checked?

**Comment by MrMEEE** [comment]
Please also check to see if rabbitmq is running
```
systemctl status rabbitmq-server
```

**Comment by ainaomotayo** [comment]
@MrMEEE: Thank you for the quick response.
> 
> 
> Please also check to see if rabbitmq is running
> 
> ```
> systemctl status rabbitmq-server
> ```

RabbitMQ is running fine
● rabbitmq-server.service - RabbitMQ broker
   Loaded: loaded (/usr/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-09-16 14:17:23 EAT; 1min 2s ago
  Process: 1471 ExecStop=/usr/lib/rabbitmq/bin/rabbitmqctl stop (code=exited, status=0/SUCCESS)
 Main PID: 1547 (beam)
   CGroup: /system.slice/rabbitmq-server.service
           ├─1547 /usr/lib64/erlang/erts-5.10.4/bin/beam -W w -K true -A30 -P 1048576 -- -root /usr/lib64/er...
           ├─1564 /usr/lib64/erlang/erts-5.10.4/bin/epmd -daemon
           ├─1658 inet_gethost 4
           └─1659 inet_gethost 4

Sep 16 14:16:52 master systemd[1]: Starting RabbitMQ broker...
Sep 16 14:16:54 master systemd[1]: rabbitmq-server.service: Got notification message from PID 1564, but... 1547
Sep 16 14:17:19 master rabbitmq-server[1547]: RabbitMQ 3.3.5. Copyright (C) 2007-2014 GoPivotal, Inc.
Sep 16 14:17:19 master rabbitmq-server[1547]: ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
Sep 16 14:17:19 master rabbitmq-server[1547]: ##  ##
Sep 16 14:17:19 master rabbitmq-server[1547]: ##########  Logs: /var/log/rabbitmq/rabbit@master.log
Sep 16 14:17:19 master rabbitmq-server[1547]: ######  ##        /var/log/rabbitmq/rabbit@master-sasl.log
Sep 16 14:17:19 master rabbitmq-server[1547]: ##########
Sep 16 14:17:23 master systemd[1]: Started RabbitMQ broker.
Sep 16 14:17:23 master rabbitmq-server[1547]: Starting broker... completed with 0 plugins.

**Comment by MrMEEE** [comment]
How about the "systemctl status awx-*"?

**Comment by ainaomotayo** [comment]
> 
> 
> How about the "systemctl status awx-*"?

systemctl status awx-*
● awx-cbreceiver.service - AWX cbreceiver service
   Loaded: loaded (/usr/lib/systemd/system/awx-cbreceiver.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-09-16 14:16:46 EAT; 4min 22s ago
 Main PID: 1466 (scl)
   CGroup: /system.slice/awx-cbreceiver.service
           ├─1466 /usr/bin/scl enable rh-python36 rh-postgresql10 awx-manage run_callback_receiver
           ├─1473 /bin/bash /var/tmp/sclZXbxEv
           ├─1510 /opt/rh/rh-python36/root/usr/bin/python3 /opt/rh/rh-python36/root/usr/bin/awx-manage run_c...
           ├─1702 /opt/rh/rh-python36/root/usr/bin/python3 /opt/rh/rh-python36/root/usr/bin/awx-manage run_c...
           ├─1703 /opt/rh/rh-python36/root/usr/bin/python3 /opt/rh/rh-python36/root/usr/bin/awx-manage run_c...
           ├─1704 /opt/rh/rh-python36/root/usr/bin/python3 /opt/rh/rh-python36/root/usr/bin/awx-manage run_c...
           └─1705 /opt/rh/rh-python36/root/usr/bin/python3 /opt/rh/rh-python36/root/usr/bin/awx-manage run_c...

Sep 16 14:16:46 master systemd[1]: Started AWX cbreceiver service.
Sep 16 14:17:59 master scl[1466]: 2019-09-16 11:17:59,048 WARNING  awx.main.commands.run_callback_recei...:1702
Sep 16 14:17:59 master scl[1466]: 2019-09-16 11:17:59,048 WARNING  awx.main.commands.run_callback_recei...:1702
Sep 16 14:17:59 master scl[1466]: 2019-09-16 11:17:59,148 WARNING  awx.main.commands.run_callback_recei...:1703
Sep 16 14:17:59 master scl[1466]: 2019-09-16 11:17:59,148 WARNING  awx.main.commands.run_callback_recei...:1703
Sep 16 14:17:59 master scl[1466]: 2019-09-16 11:17:59,255 WARNING  awx.main.commands.run_callback_recei...:1704
Sep 16 14:17:59 master scl[1466]: 2019-09-16 11:17:59,255 WARNING  awx.main.commands.run_callback_recei...:1704
Sep 16 14:17:59 master scl[1466]: 2019-09-16 11:17:59,307 WARNING  awx.main.commands.run_callback_recei...:1705
Sep 16 14:17:59 master scl[1466]: 2019-09-16 11:17:59,307 WARNING  awx.main.commands.run_callback_recei...:1705

● awx-channels-worker.service - AWX channels worker service
   Loaded: loaded (/usr/lib/systemd/system/awx-channels-worker.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-09-16 14:16:46 EAT; 4min 22s ago
 Main PID: 1467 (scl)
   CGroup: /system.slice/awx-channels-worker.service
           ├─1467 /usr/bin/scl enable rh-python36 rh-postgresql10 awx-manage runworker --only-channels 'webs...
           ├─1472 /bin/bash /var/tmp/sclRMbQSx
           └─1509 /opt/rh/rh-python36/root/usr/bin/python3 /opt/rh/rh-python36/root/usr/bin/awx-manage runwo...

Sep 16 14:16:46 master systemd[1]: Started AWX channels worker service.
Sep 16 14:18:00 master scl[1467]: 2019-09-16 11:18:00,363 - INFO - runworker - Using single-threaded worker.
Sep 16 14:18:00 master scl[1467]: 2019-09-16 11:18:00,364 - INFO - runworker - Running worker against c...ayer)
Sep 16 14:18:00 master scl[1467]: 2019-09-16 11:18:00,366 - INFO - worker - Listening on channels webso...ceive

● awx-web.service - AWX web service
   Loaded: loaded (/usr/lib/systemd/system/awx-web.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-09-16 14:16:46 EAT; 4min 22s ago
 Main PID: 1464 (scl)
   CGroup: /system.slice/awx-web.service
           ├─1464 /usr/bin/scl enable rh-python36 rh-postgresql10 uwsgi          --socket 127.0.0.1:8050    ...
           ├─1468 /bin/bash /var/tmp/sclhK6tOt
           ├─1513 uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/tower/web.log...
           ├─1533 uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/tower/web.log...
           ├─1535 uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/tower/web.log...
           ├─1536 uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/tower/web.log...
           ├─1537 uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/tower/web.log...
           └─1539 uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/tower/web.log...

Sep 16 14:16:46 master systemd[1]: Started AWX web service.

● awx-daphne.service - AWX daphne service
   Loaded: loaded (/usr/lib/systemd/system/awx-daphne.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-09-16 14:16:46 EAT; 4min 22s ago
 Main PID: 1465 (scl)
   CGroup: /system.slice/awx-daphne.service
           ├─1465 /usr/bin/scl enable rh-python36 rh-postgresql10 daphne -b 127.0.0.1 -p 8051 awx.asgi:chann...
           ├─1469 /bin/bash /var/tmp/sclE9AY1s
           └─1514 /opt/rh/rh-python36/root/usr/bin/python3 /opt/rh/rh-python36/root/usr/bin/daphne -b 127.0....

Sep 16 14:16:46 master systemd[1]: Started AWX daphne service.
Sep 16 14:17:45 master scl[1465]: 2019-09-16 11:17:44,884 INFO     Starting server at tcp:port=8051:int...ayer.
Sep 16 14:17:45 master scl[1465]: 2019-09-16 11:17:45,269 INFO     HTTP/2 support not enabled (install ...tras)
Sep 16 14:17:45 master scl[1465]: 2019-09-16 11:17:45,269 INFO     Using busy-loop synchronous mode on ...layer
Sep 16 14:17:45 master scl[1465]: 2019-09-16 11:17:45,269 INFO     Listening on endpoint tcp:port=8051:...0.0.1
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by MrMEEE** [comment]
Seems like the dispatcher service is missing?

systemctl status awx-dispatcher

**Comment by ainaomotayo** [comment]
> 
> 
> Seems like the dispatcher service is missing?
> 
> systemctl status awx-dispatcher

Is not running before.

Is running now but job is showing failed
![image](https://user-images.githubusercontent.com/17462342/64954567-b54a1e80-d88e-11e9-9f82-bdc8e8d557ac.png)

**Comment by MrMEEE** [comment]
Does it work if you start a new job?

**Comment by ainaomotayo** [comment]
> 
> 
> Does it work if you start a new job?

Is showing error on a new job
![image](https://user-images.githubusercontent.com/17462342/64954974-b760ad00-d88f-11e9-9316-efe0d569ccfa.png)

**Comment by MrMEEE** [comment]
does updating the project work?

**Comment by ainaomotayo** [comment]
Yes

**Comment by MrMEEE** [comment]
Also, try refreshing the window.. if the job fails before the windows is loaded, no output is show.. but if you refresh/reload, you might see the error

**Comment by ainaomotayo** [comment]
Is still same... just failed with no output shown

**Comment by MrMEEE** [comment]
How about logs and journalctl?

**Comment by ainaomotayo** [comment]
> 
> 
> How about logs and journalctl?

 cat /var/log/tower/dispatcher.log
2019-09-16 11:24:58,968 WARNING  awx.main.dispatch PID:1811 scaling up worker pid:1825
2019-09-16 11:24:59,151 WARNING  awx.main.dispatch PID:1811 scaling up worker pid:1826
2019-09-16 11:24:59,222 WARNING  awx.main.dispatch PID:1811 scaling up worker pid:1827
2019-09-16 11:24:59,277 WARNING  awx.main.dispatch PID:1811 scaling up worker pid:1828
2019-09-16 11:25:32,702 WARNING  awx.main.dispatch PID:1825 project_update 2 (error) encountered an error (rc=None), please see task stdout for details.
2019-09-16 11:25:34,867 WARNING  awx.main.dispatch PID:1828 job 7 (error) encountered an error (rc=None), please see task stdout for details.
2019-09-16 11:25:35,428 WARNING  awx.main.dispatch PID:1811 scaling up worker pid:1855
2019-09-16 11:25:36,970 WARNING  awx.main.dispatch PID:1827 job 3 (error) encountered an error (rc=None), please see task stdout for details.
2019-09-16 11:25:38,909 WARNING  awx.main.dispatch PID:1825 job 4 (error) encountered an error (rc=None), please see task stdout for details.
2019-09-16 11:26:06,253 WARNING  awx.main.dispatch PID:1811 scaling down worker pid:1825
2019-09-16 11:26:06,279 WARNING  awx.main.dispatch PID:1825 worker exiting gracefully pid:1825
2019-09-16 11:28:57,326 WARNING  awx.main.dispatch PID:1826 project_update 9 (error) encountered an error (rc=None), please see task stdout for details.
2019-09-16 11:29:23,477 WARNING  awx.main.dispatch PID:1855 project_update 11 (error) encountered an error (rc=None), please see task stdout for details.
2019-09-16 11:37:18,985 WARNING  awx.main.dispatch PID:1855 job 12 (error) encountered an error (rc=None), please see task stdout for details.
2019-09-16 11:41:47,353 WARNING  awx.main.dispatch PID:1826 project_update 13 (error) encountered an error (rc=None), please see task stdout for details.
2019-09-16 11:42:07,188 WARNING  awx.main.dispatch PID:1827 project_update 14 (error) encountered an error (rc=None), please see task stdout for details.
2019-09-16 11:42:40,452 WARNING  awx.main.dispatch PID:1827 project_update 16 (error) encountered an error (rc=None), please see task stdout for details.
2019-09-16 11:48:18,846 WARNING  awx.main.dispatch PID:1826 project_update 18 (error) encountered an error (rc=None), please see task stdout for details.
2019-09-16 11:48:39,478 WARNING  awx.main.dispatch PID:1826 project_update 20 (error) encountered an error (rc=None), please see task stdout for details.
2019-09-16 11:48:55,978 WARNING  awx.main.dispatch PID:1826 project_update 22 (error) encountered an error (rc=None), please see task stdout for details.
2019-09-16 11:49:30,386 WARNING  awx.main.dispatch PID:1826 project_update 23 (error) encountered an error (rc=None), please see task stdout for details.
[JournalCTL.txt](https://github.com/MrMEEE/awx-build/files/3616125/JournalCTL.txt)

Please find journalctl attached

**Comment by MrMEEE** [comment]
Guess this is your error:

```
Sep 16 14:25:36 master scl[1804]: 2019-09-16 11:25:36,970 WARNING  awx.main.dispatch job 3 (error) encountered an error (rc=None), please see task stdout for details.
Sep 16 14:25:38 master scl[1804]: 2019-09-16 11:25:38,536 ERROR    awx.main.tasks job 4 (running) Exception occurred while running task
Sep 16 14:25:38 master scl[1804]: Traceback (most recent call last):
Sep 16 14:25:38 master scl[1804]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/tasks.py", line 1165, in run
Sep 16 14:25:38 master scl[1804]: self.pre_run_hook(self.instance, private_data_dir)
Sep 16 14:25:38 master scl[1804]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/tasks.py", line 1611, in pre_run_hook
Sep 16 14:25:38 master scl[1804]: raise RuntimeError(msg)
Sep 16 14:25:38 master scl[1804]: RuntimeError: The project revision for this job template is unknown due to a failed update.
```
Have you just installed, or upgraded?

**Comment by MrMEEE** [comment]
Maybe this is related:
https://github.com/ansible/awx/issues/4418

**Comment by MrMEEE** [comment]
Found another error:
```
Sep 16 14:48:18 master scl[1804]: 2019-09-16 11:48:18,000 ERROR    awx.main.tasks project_update 18 (running) Invalid virtual environment selected: /opt/rh/rh-python36/root/
```
try changing the virtual environment

**Comment by MrMEEE** [comment]
You also have some network issues:
```
Sep 16 14:58:38 master NetworkManager[682]: <warn>  [1568635118.1254] acd[0x55618ca12600,2]: conflict for address 192.168.224.145 detected with host 00:0C:29:64:27:58 on interface 'ens33'
```

**Comment by ainaomotayo** [comment]
I installed it last week.
I will change the virtual environment and report the progress. 
Please how can I install the previous version awx version 5?

**Comment by Ashjoker24** [comment]
@ainaomotayo I reinstalled AWX and now it's works fine and after that i found the error was in my network issue
