### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by bluikko** [MrMEEE/awx-build#217]
Is this project still alive?

AWX is now at 9.2.0 but there is no movement since December. I wish it is only temporary since the maintainer did really good job!

**Comment by MrMEEE** [comment]
Why do you say that there has been no movement since December?

**Comment by flynn1973** [comment]
maybe because the wiki was not updated for a while, new packages are available anyway.

root@lpgaixmgmtlx01:/root/python_scripts>yum update ansible-awx
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Resolving Dependencies
--> Running transaction check
---> Package ansible-awx.ppc64le 0:9.1.1.9-1.el7 will be updated
---> Package ansible-awx.ppc64le 0:9.2.0.164-1.el7 will be an update
--> Finished Dependency Resolution

**Comment by bluikko** [comment]
I see. I actually only looked at awx.wiki and the commit history, silly me.

I will test the standard upgrade process from December's release to current then.
