### ISSUE TITLE
Project awx-build

### ISSUE THREAD

**Issue by kyklos** [MrMEEE/awx-build#283]
Is the project still being maintained and will future AWX updates be expected? I ask because AWX 14.1.0 has already been released.

**Comment by MrMEEE** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Hi DanYes, this project is being maintained, but is under a complete rewrite.. Timeline for next release is 2-3 months... after which there will be frequent updates..                                                                                                                                             Sendt fra min BlackBerry - den sikreste mobilenhed                                                                                                                                                                           Fra: notifications@github.comSendt: 8. september 2020 13.23Til: awx-build@noreply.github.comSvar til: reply@reply.github.comCc: subscribed@noreply.github.comEmne: [MrMEEE/awx-build] Project (#283)  
Is the project still being maintained and will future AWX updates be expected? I ask because AWX 14.1.0 has already been released.

**Comment by kyklos** [comment]
Great news. Thanks for the information and good luck

**Comment by kyklos** [comment]
...
