### ISSUE TITLE
Issues during install "awx-manage not found"

### ISSUE THREAD

**Issue by sarman-tftsr** [MrMEEE/awx-build#323]
I am having the same issue. My install is on Rocky 8 (CentOS8 based). This is the section it keeps failing:

```TASK [miracle-ansible-role-awxrpm-scl-installer : Run awxprepare] ************************************************* fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/awxprepare.sh", "delta": "0:00:00.013633", "end": "2022-01-22 00:56:45.511853", "msg": "non-zero return code", "rc": 2, "start": "2022-01-22 00:56:45.498220", "stderr": "/var/tmp/sclK1PBoS: line 5: awx-manage: command not found\n/usr/local/bin/awxprepare.sh: line 5: syntax error near unexpected token 'admin','\n/usr/local/bin/awxprepare.sh: line 5: echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')\" | GIT_PYTHON_REFRESH=quiet scl enable miracle-awxrpm \"awx-manage shell \"'", "stderr_lines": ["/var/tmp/sclK1PBoS: line 5: awx-manage: command not found", "/usr/local/bin/awxprepare.sh: line 5: syntax error near unexpected token 'admin','", "/usr/local/bin/awxprepare.sh: line 5: echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')\" | GIT_PYTHON_REFRESH=quiet scl enable miracle-awxrpm \"awx-manage shell \"'"], "stdout": "", "stdout_lines": []}```

I have tried many times to even load awx-manage local, installed Ansible-tower-cli. Any suggestions or ideas?

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/

**Comment by MrMEEE** [comment]
Hi guys

It's been some time.. And I know that there have been a lot of promises, and few of them have been kept..

The AWX-RPM project is back under my wings, and I hope push out new builds as fast as I can..

Recent work from the CentOS community and Red hat has made dependency building A LOT easier.. it's not perfect yet (and probably never will be), but it will make maintenance of the RPMS a lot less time consuming.

Because of this I have decided to completely reignite the AWX-RPM project, scrap all the old work (but keep the know-how) and if you want to follow the progress, follow this new repo, which will also be where new issues can be reported in time..

https://lnkd.in/epXMaiAN

Right now I'm trying to build something to handle dependency building and exceptions to the depbuilding process... this is about 80% of the work..

From there I'll create the AWX-RPM core and services files and at some point create an installer..

When the core and services files are done, I'll see the project as Beta and ready for testing.. I hope this will happen within february, but it all depends on work pressure and family, so have patience.

However, when this is done, I'm really confident that automatic builds should be rolling out without needing much effort from my side.

Thanks for all your patience, support and feedback.

Talk to you all soon..
