### ISSUE TITLE
error while install centos8

### ISSUE THREAD

**Issue by junnbj** [MrMEEE/awx-build#324]
Can you help me?
I found some errors and try to ignore, but the app dont work:

TASK [miracle-ansible-role-awxrpm-scl-installer : Enable SELinux in enforcing mode] *********************************************************************************************************
fatal: [ansible-centos8-final]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'selinuxstate' is undefined\n\nThe error appears to be in '/home/awx/.ansible/roles/miracle-ansible-role-awxrpm-scl-installer/tasks/prepare-server.yml': line 130, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable SELinux in enforcing mode\n  ^ here\n"}
...ignoring

TASK [miracle-ansible-role-awxrpm-scl-installer : Install PostgreSQL] ***********************************************************************************************************************
fatal: [ansible-centos8-final]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'postgresqlversion' is undefined\n\nThe error appears to be in '/home/awx/.ansible/roles/miracle-ansible-role-awxrpm-scl-installer/tasks/install-postgres.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install PostgreSQL\n  ^ here\n"}
...ignoring

TASK [miracle-ansible-role-awxrpm-scl-installer : Install nodejs] ***************************************************************************************************************************
fatal: [ansible-centos8-final]: FAILED! => {"changed": false, "msg": "No group nodejs:v14.x/common available.", "results": []}
...ignoring

TASK [miracle-ansible-role-awxrpm-scl-installer : Run awxprepare] ***************************************************************************************************************************
fatal: [ansible-centos8-final]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/awxprepare.sh", "delta": "0:00:00.019146", "end": "2022-06-02 18:49:03.648585", "msg": "non-zero return code", "rc": 2, "start": "2022-06-02 18:49:03.629439", "stderr": "/var/tmp/sclPAPQNH: line 5: awx-manage: command not found\n/usr/local/bin/awxprepare.sh: line 5: syntax error near unexpected token `'admin','\n/usr/local/bin/awxprepare.sh: line 5: `echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')\" | GIT_PYTHON_REFRESH=quiet scl enable miracle-awxrpm \"awx-manage shell \"'", "stderr_lines": ["/var/tmp/sclPAPQNH: line 5: awx-manage: command not found", "/usr/local/bin/awxprepare.sh: line 5: syntax error near unexpected token `'admin','", "/usr/local/bin/awxprepare.sh: line 5: `echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')\" | GIT_PYTHON_REFRESH=quiet scl enable miracle-awxrpm \"awx-manage shell \"'"], "stdout": "", "stdout_lines": []}
...ignoring

**Comment by fbraz3** [comment]
same error here!

**Comment by MrMEEE** [comment]
Hi guys

It's been some time.. And I know that there have been a lot of promises, and few of them have been kept..

The AWX-RPM project is back under my wings, and I hope push out new builds as fast as I can..

Recent work from the CentOS community and Red hat has made dependency building A LOT easier.. it's not perfect yet (and probably never will be), but it will make maintenance of the RPMS a lot less time consuming.

Because of this I have decided to completely reignite the AWX-RPM project, scrap all the old work (but keep the know-how) and if you want to follow the progress, follow this new repo, which will also be where new issues can be reported in time..

https://lnkd.in/epXMaiAN

Right now I'm trying to build something to handle dependency building and exceptions to the depbuilding process... this is about 80% of the work..

From there I'll create the AWX-RPM core and services files and at some point create an installer..

When the core and services files are done, I'll see the project as Beta and ready for testing.. I hope this will happen within february, but it all depends on work pressure and family, so have patience.

However, when this is done, I'm really confident that automatic builds should be rolling out without needing much effort from my side.

Thanks for all your patience, support and feedback.

Talk to you all soon..
