### ISSUE TITLE
Need steps to upgrade awxtower 11.2.0 to latest version

### ISSUE THREAD

**Issue by chaitanya486-sys** [MrMEEE/awx-build#325]
can you please provide steps to upgrade awx tower 11.2.0 to the latest version

**Comment by MrMEEE** [comment]
Hi guys

It's been some time.. And I know that there have been a lot of promises, and few of them have been kept..

The AWX-RPM project is back under my wings, and I hope push out new builds as fast as I can..

Recent work from the CentOS community and Red hat has made dependency building A LOT easier.. it's not perfect yet (and probably never will be), but it will make maintenance of the RPMS a lot less time consuming.

Because of this I have decided to completely reignite the AWX-RPM project, scrap all the old work (but keep the know-how) and if you want to follow the progress, follow this new repo, which will also be where new issues can be reported in time..

https://lnkd.in/epXMaiAN

Right now I'm trying to build something to handle dependency building and exceptions to the depbuilding process... this is about 80% of the work..

From there I'll create the AWX-RPM core and services files and at some point create an installer..

When the core and services files are done, I'll see the project as Beta and ready for testing.. I hope this will happen within february, but it all depends on work pressure and family, so have patience.

However, when this is done, I'm really confident that automatic builds should be rolling out without needing much effort from my side.

Thanks for all your patience, support and feedback.

Talk to you all soon..
