### ISSUE TITLE
awx-manage command not found

### ISSUE THREAD

**Issue by gravelander** [MrMEEE/awx-build#91]
I've gone through the [installation guide](https://github.com/MrMEEE/awx-build/blob/master/installguide.md), copying word-for-word but when I get to the "Configuring AWX" part, there is no awx-manage command to proceed.

Perhaps it's not listed in the installation?

**Comment by MrMEEE** [comment]
Hi

Are you sure that you are using the software collections enabler??

example: sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage create_preload_data"

awx-manage is in the ansible-awx package:

[root@akiva]# rpm -ql ansible-awx |grep awx-manage
/opt/rh/rh-python36/root/usr/bin/awx-manage

but is only usable with the rh-python36 software collection..

**Comment by MrMEEE** [comment]
Did you get this to work??

**Comment by bwosborne** [comment]
You must have selected the stable repo. It is broken and does not install awx.  I tried changing repos but am now reinstalling my os to try again with a clean install.

I am using CentOS 7. Reinstallation seems to work with the dev repo.

**Comment by MrMEEE** [comment]
Closing.. please reopen if this persists

**Comment by sarman-tftsr** [comment]
I am having the same issue. My install is on Rocky 8 (CentOS8 based). This is the section it keeps failing:
`TASK [miracle-ansible-role-awxrpm-scl-installer : Run awxprepare] *************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/awxprepare.sh", "delta": "0:00:00.013633", "end": "2022-01-22 00:56:45.511853", "msg": "non-zero return code", "rc": 2, "start": "2022-01-22 00:56:45.498220", "stderr": "/var/tmp/sclK1PBoS: line 5: awx-manage: command not found\n/usr/local/bin/awxprepare.sh: line 5: syntax error near unexpected token `'admin','\n/usr/local/bin/awxprepare.sh: line 5: `echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')\" | GIT_PYTHON_REFRESH=quiet scl enable miracle-awxrpm \"awx-manage shell \"'", "stderr_lines": ["/var/tmp/sclK1PBoS: line 5: awx-manage: command not found", "/usr/local/bin/awxprepare.sh: line 5: syntax error near unexpected token `'admin','", "/usr/local/bin/awxprepare.sh: line 5: `echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')\" | GIT_PYTHON_REFRESH=quiet scl enable miracle-awxrpm \"awx-manage shell \"'"], "stdout": "", "stdout_lines": []}`

I have tried many times to even load awx-manage local, installed Ansible-tower-cli. Any suggestions or ideas?

**Comment by fesm788m** [comment]
I was having this issue when i tried to re-install an ansible-tower instalation , Somehow when i uninstalled old version a file was wandering there and i needed to delete it in order to pass this errror about awx-manage not found.

After i ran the setup.sh to reinstall ansible tower i was getting this error 
TASK [preflight : Preflight check - check Tower license type] ************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "awx-manage check_license", "delta": "0:00:00.003382", "end": "2023-04-20 13:50:51.503618", "msg": "non-zero return code", "rc": 127, "start": "2023-04-20 13:50:51.500236", "stderr": "/bin/sh: awx-manage: command not found", "stderr_lines": ["/bin/sh: awx-manage: command not found"], "stdout": "", "stdout_lines": []}

 
After digging and checking logs i noticed somehow a file was being kept there from old ansible tower instalation (/var/lib/awx/.tower_version), so i deleted that single file and it fixed my issue and i was able to re run sudo ./setup.sh

In addition i would like to say, in my case, that awx-manage is available as well in servers installations of ansible-tower not only in docker installation (as many articles found in internet assure) , after i finished my ansible tower reInstalation i can see awx-manage available in my server:

*Somehow that file from the old installation ((/var/lib/awx/.tower_version) was preventing my system to install again awx-manage from watever repo it came.

[user@localhost ansible-tower-setup]$ awx-
awx-manage  awx-python
[user@localhost ansible-tower-setup]$ which awx-manage
/usr/bin/awx-manage

**Comment by MrMEEE** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  HiThis repo is deprecated..Please look into https://github.com/MrMEEE/awx-rpm-v2Thanks..                                                                                                                                             Sendt fra min BlackBerry - den sikreste mobilenhed                                                                                                                                                                           Fra: ***@***.***: 20. april 2023 18.40Til: ***@***.*** til: ***@***.***: ***@***.***; ***@***.***: Re: [MrMEEE/awx-build] awx-manage command not found (#91)  
I was having this issue when i tried to re-install an ansible-tower instalation , Somehow when i uninstalled old version a file was wandering there and i needed to delete it in order to pass this errror about awx-manage not found.
After i ran the setup.sh to reinstall ansible tower i was getting this error
TASK [preflight : Preflight check - check Tower license type] ************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "awx-manage check_license", "delta": "0:00:00.003382", "end": "2023-04-20 13:50:51.503618", "msg": "non-zero return code", "rc": 127, "start": "2023-04-20 13:50:51.500236", "stderr": "/bin/sh: awx-manage: command not found", "stderr_lines": ["/bin/sh: awx-manage: command not found"], "stdout": "", "stdout_lines": []}
After digging and checking logs i noticed somehow a file was being kept there from old ansible tower instalation (/var/lib/awx/.tower_version), so i deleted that single file and it fixed my issue and i was able to re run sudo ./setup.sh
In addition i would like to say, in my case, that awx-manage is available as well in servers installations of ansible-tower not only in docker installation (as many articles found in internet assure) , after i finished my ansible tower reInstalation i can see awx-manage available in my server:
*Somehow that file from the old installation ((/var/lib/awx/.tower_version) was preventing my system to install again awx-manage from watever repo it came.
***@***.*** ansible-tower-setup]$ awx-
awx-manage  awx-python
***@***.*** ansible-tower-setup]$ which awx-manage
/usr/bin/awx-manage
